version: '3'
services:
  load-balancer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BACKEND_SERVERS=http://172.27.167.40:8081/,http://172.27.167.40:8082/
    ports:
      - "8080:8080"
